export const COUNTRY_OPTIONS = [
  { label: "爱尔兰", value: "IE" },
  { label: "澳大利亚", value: "AU" },
  { label: "巴西", value: "BR" },
  { label: "比利时", value: "BE" },
  { label: "波兰", value: "PL" },
  { label: "丹麦", value: "DK" },
  { label: "德国", value: "DE" },
  { label: "俄罗斯", value: "RU" },
  { label: "法国", value: "FR" },
  { label: "韩国", value: "KR" },
  { label: "荷兰", value: "NL" },
  { label: "加拿大", value: "CA" },
  { label: "美国", value: "US" },
  { label: "墨西哥", value: "MX" },
  { label: "挪威", value: "NO" },
  { label: "日本", value: "JP" },
  { label: "瑞典", value: "SE" },
  { label: "沙特阿拉伯", value: "SA" },
  { label: "泰国", value: "TH" },
  { label: "西班牙", value: "ES" },
  { label: "意大利", value: "IT" },
  { label: "印度", value: "IN" },
  { label: "英国", value: "GB" },
  { label: "中国澳门", value: "MO" },
  { label: "中国大陆", value: "CN" },
  { label: "中国台湾", value: "TW" },
  { label: "中国香港", value: "HK" }
]

export const GENRE_OPTIONS = [
  { label: "爱情", value: "10749" },
  { label: "电视电影", value: "10770" },
  { label: "动画", value: "16" },
  { label: "动作", value: "28" },
  { label: "动作冒险", value: "10759" },
  { label: "儿童", value: "10762" },
  { label: "犯罪", value: "80" },
  { label: "肥皂剧", value: "10766" },
  { label: "纪录片", value: "99" },
  { label: "家庭", value: "10751" },
  { label: "惊悚", value: "53" },
  { label: "剧情", value: "18" },
  { label: "科幻", value: "878" },
  { label: "科幻奇幻", value: "10765" },
  { label: "恐怖", value: "27" },
  { label: "历史", value: "36" },
  { label: "冒险", value: "12" },
  { label: "奇幻", value: "14" },
  { label: "脱口秀", value: "10767" },
  { label: "西部", value: "37" },
  { label: "喜剧", value: "35" },
  { label: "新闻", value: "10763" },
  { label: "悬疑", value: "9648" },
  { label: "音乐", value: "10402" },
  { label: "战争", value: "10752" },
  { label: "战争政治", value: "10768" },
  { label: "真人秀", value: "10764" }
]

export const ITEM_TYPE_OPTIONS = [
  { label: '全部', value: 'all' },
  { label: '仅电影', value: 'movie' },
  { label: '仅剧集', value: 'series' }
]